RNG_SEED: 1409
ENV:
  MODULES: ["Agent", "Terrain", "Objects"]
  KEYS_TO_KEEP: ["hfield"]
  TASK: "bump"
MODEL:
  TRANSFORMER:
    EXT_HIDDEN_DIMS: [64, 64]
    DECODER_DIMS: [64, 64]
    EXT_MIX: "late"
TERRAIN:
  SIZE: [50, 20, 1]
  START_FLAT: 3
  FLAT_LENGTH_RANGE: [50, 20, 1]
  TYPES: ["flat"]
  BOUNDARY_WALLS: True
HFIELD:
  OBS_SIZE: [1, 4, 4, 4]
OBJECT:
  NUM_BUMPS: 250
  BUMP_LEN_RANGE: [0.8, 1.6, 0.2]
  BUMP_WIDTH_RANGE: [0.8, 1.6, 0.2]
  BUMP_HEIGHT_RANGE: [0.1, 0.25, 0.05]
  PLACEMENT_BUFFER_LEN: 5
  PLACEMENT_BUFFER_WIDTH: 0