RNG_SEED: 1409
ENV:
  MODULES: ["Agent", "Terrain", "Objects"]
  KEYS_TO_KEEP: ["hfield"]
  TASK: "obstacle"
MODEL:
  TRANSFORMER:
    EXT_HIDDEN_DIMS: [64, 64]
    DECODER_DIMS: [64, 64]
    EXT_MIX: "late"
TERRAIN:
  SIZE: [50, 20, 1]
  START_FLAT: 3
  FLAT_LENGTH_RANGE: [50, 20, 1]
  TYPES: ["flat"]
  BOUNDARY_WALLS: True
HFIELD:
  OBS_SIZE: [1, 4, 4, 4]